steps:
  # 1. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        # --- PERUBAHAN DI SINI ---
        'us-east4-docker.pkg.dev/$PROJECT_ID/summarize-api/summarize-api:latest', 
        '.', # Build dari root project
        '-f', # Tentukan Dockerfile secara eksplisit
        'summarize-me-api/Dockerfile' # Path Dockerfile
      ]

  # 2. Push image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        # --- PERUBAHAN DI SINI ---
        'us-east4-docker.pkg.dev/$PROJECT_ID/summarize-api/summarize-api:latest'
      ]

  # 3. Deploy ke Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'summarize-api', # Nama service Cloud Run
        '--image', 'us-east4-docker.pkg.dev/$PROJECT_ID/summarize-api/summarize-api:latest',
        # --- PERUBAHAN DI SINI ---
        '--region', 'us-east4',
        '--platform', 'managed',
        '--allow-unauthenticated', # Sesuaikan jika perlu autentikasi IAM/IAP
        '--port', '8080',
        # ... (sisa env-vars Anda)
      ]

# Substitutions (opsional)
substitutions:
  _SERVICE_NAME: 'summarize-api'
  # --- PERUBAHAN DI SINI ---
  _REGION: 'us-east4'

options:
  logging: CLOUD_LOGGING_ONLY