steps:
  # Build image (ganti path ke Artifact Registry baru Anda)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      # UBAH INI: (ganti 'asia-southeast1' ke 'us-central1' dan sesuaikan nama repo)
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/summarize-me-repo-us/summarize-me-api:latest' 
      - '.'

  # Push image (ganti path juga)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      # UBAH INI:
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/summarize-me-repo-us/summarize-me-api:latest'

  # Deploy ke Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - 'summarize-me-api'
      - '--image'
      # UBAH INI:
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/summarize-me-repo-us/summarize-me-api:latest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

# ... (sisa file) ...
images:
  # UBAH INI:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/summarize-me-repo-us/summarize-me-api:latest'